# Path-based PR labeling configuration
# https://github.com/actions/labeler

web:
  - changed-files:
      - any-glob-to-any-file: 'apps/web/**'

api:
  - changed-files:
      - any-glob-to-any-file: 'apps/api/**'

parser:
  - changed-files:
      - any-glob-to-any-file: 'packages/htoprc-parser/**'

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**'

github_actions:
  - changed-files:
      - any-glob-to-any-file: '.github/**'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'package.json'
          - 'pnpm-lock.yaml'
          - '**/package.json'

config:
  - changed-files:
      - any-glob-to-any-file:
          - '*.json'
          - '*.yaml'
          - '*.yml'
          - '*.toml'
          - '.nvmrc'
          - '.gitignore'
